apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zama-pevm-testnet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/haroldsphinx/zama.git
    targetRevision: main
    path: k8s/zama-pevm-testnet-job

  destination:
    server: https://kubernetes.default.svc
    namespace: zama-pevm-testnet

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
