apiVersion: v1
kind: ConfigMap
metadata:
  name: network-params
  namespace: zama-pevm-testnet
data:
  network_params.yaml: |
    participants:
      - el_type: geth
        cl_type: lighthouse
        count: 2
        validator_count: 32
        el_extra_params:
          - "--syncmode=full"

      - el_type: geth
        cl_type: lighthouse
        count: 1
        validator_count: 0
        el_extra_params:
          - "--syncmode=full"
          - "--http.vhosts=*"
          - "--http.corsdomain=*"

    network_params:
      network_id: "12345"
      fulu_fork_epoch: 18446744073709551615
      electra_fork_epoch: 0

    additional_services:
      - blockscout
      - prometheus_grafana
      - assertoor
