apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurtosis-deployer
  namespace: zama-pevm-testnet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kurtosis-deployer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kurtosis-deployer
    namespace: zama-pevm-testnet
